### ISSUE TITLE
lastbgs search tag partial matching

### ISSUE THREAD

**Issue by awaxa** [discord-diabetes/diabot-plugins#5]
I notice users unintentionally adding complexity to their tags with punctuation and so forth.  Perhaps partial matching in last/lastbgs is in order?  Eg: should break match just "break" or "break*" so that searches for "tag" when the stored tag is "tag!" or "tag?" will include the punctuated results?

**Comment by TwelveBaud** [comment]
I'm thinking the right thing to do is strip punctuation from the tags before doing comparisons, but to require exact matches otherwise. This will encourage users to tag appropriately, but not punish them for exclamation marks and such. Perhaps an article filter also needs to be considered (remove "a", "and", "the", etc).

**Comment by TwelveBaud** [comment]
a3c9675fae409a10c082075cf9a9f3e3e5c7ad75 _hopefully_ makes it so that punctuation is stripped from new tags as they're entered.
